name: Validate JSON Schema

on:
  pull_request:
    paths:
      - 'dApps/*.json'
      - 'dapp-schema.json'
  push:
    branches: [ main ]
    paths:
      - 'dApps/*.json'
      - 'dapp-schema.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    
    - name: Validate JSON files
      run: python scripts/validate_json.py